version: "3.9"

services:
  backend:
    image: backend:latest
    build: ./Backend
    env_file:
      - .env
    container_name: backend
    environment:
      - BACKEND_DEV_URL=${BACKEND_DEV_URL}
      - GNEWS_API_KEY=${GNEWS_API_KEY}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    restart: unless-stopped
    network_mode: host
    ports:
      - 7156:7156

  frontend:
    image: frontend:latest
    build: ./Frontend
    container_name: frontend
    environment:
      - BACKEND_DEV_URL=${BACKEND_DEV_URL}
      - GNEWS_API_KEY=${GNEWS_API_KEY}
    restart: unless-stopped
    network_mode: host
    depends_on:
      - backend
    ports:
      - 80:80
  


